### ISSUE TITLE
Cant install or uninstall plugins

### ISSUE THREAD

**Issue by Peronia** [portapps/android-studio-portable#17]
### Behaviour

I can't install and uninstall plugins. Disable works fine.

#### Steps to reproduce this issue

1. Install a plugin from inbuild marketplace
2. Restart the IDE
3. The plugin isn't in the list of installed plugins
4. Search the plugin on the marketplace, you can press "install" again

#### Expected behaviour

The plugin should be installed

#### Actual behaviour

The plugin isn't installed

### Configuration

**App release / arch**:

4.0.1-14 win64

**Operating system**:

Windows 10 Pro 64 bits

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/25049991/90164371-9bafa080-dd97-11ea-9139-ad0b22be6bf9.png)

### Logs

[android-studio-portable.log](https://github.com/portapps/android-studio-portable/files/5070398/android-studio-portable.log)

**Comment by crazy-max** [comment]
@Peronia I was able to reproduce your issue. Keep you in touch.

**Comment by crazy-max** [comment]
@Peronia Can you try with the latest release?

**Comment by Logic2Paradigm** [comment]
> @Peronia Can you try with the latest release?

I tried rev. 4.1.0-15 .  Plugins Flutter and Dart are not installed after "Restart IDE"

**Comment by Logic2Paradigm** [comment]
To make it work with Dart and Flutter:
1) Install Flutter and Dart from build marketplace (do not restart)
2) Download Flutter ver. 50.0.2 (latest not compatible)
    https://plugins.jetbrains.com/plugin/9212-flutter/versions
3) Unzip to \data\plugins\
4) Download Dart ver. 201-9002 (latest not compatible)
    https://plugins.jetbrains.com/plugin/6351-dart/versions
5) Unzip to \data\plugins\
6) Make new Environment System Variable: Java_HOME  path: \app\jre\
7) Restart IDE
8) Download Flutter SDK (in new project copy the path)
    https://flutter.dev/docs/development/tools/sdk/releases
9) Run from CMD:  \data\sdk\tools\bin\sdkmanager --licenses
    and accept all licenses with "y"

**Comment by Peronia** [comment]
I tried it, update and new install from plugins don't works.

**Comment by Peronia** [comment]
Is there a chance to get it fixed?

**Comment by kam92** [comment]
> Is there a chance to get it fixed?

I have tried a lot, I'm fed up with this.

The best thing to do is to go to Android Studio 
Disable plugin check for update/autoupdate.
Menubar > Help > About... See the build day.

Go to https://plugins.jetbrains.com/ 
When download version, pick the first date before the AS build date, they all work for me so far.

**Comment by ProblematicDude** [comment]
I just realized this issue is from original android studio. So i dont think you can fix this.  We should file a issue there. 
I was trying to change the config in original variant as per 
[this article](https://developer.android.com/studio/intro/studio-config#customize_ide)

I changes all the 4 properties.
1. system
2. config
3. plugin 
4. logs
To my surprise i was not able to install/uninstall any plugin.

**Comment by crazy-max** [comment]
@ProblematicDude Thanks for your feedback, that's what I thought. Can you [report this issue](https://developer.android.com/studio/report-bugs)?

**Comment by ProblematicDude** [comment]
Filed, will update the thread with further response from AS team.

**Comment by dev-techmoe** [comment]
Seems fixed on version [4.2.1-17](https://github.com/portapps/android-studio-portable/releases/tag/4.2.1-17), I'm trying to install Material Theme plugin on this version and it works without any workaround

**Comment by ProblematicDude** [comment]
@dev-techmoe  Can you please, check with some other extensions like DART or FLUTTER.

**Comment by dev-techmoe** [comment]
> @dev-techmoe Can you please, check with some other extensions like DART or FLUTTER.

I'm not good at Android development and don't know how to start a Flutter project, but seems I can install this plugin on AS and "Create a new flutter project" option has shown in the menu, is it work or not?
![image](https://user-images.githubusercontent.com/7919562/119253006-bd20a100-bbe1-11eb-992b-0f85789f63f1.png)

**Comment by ProblematicDude** [comment]
@dev-techmoe Big Thanks, this is exactly what I was asking for. **Whether dart and flutter plugins can be installed.** Thanks for letting me know that it worked.

**Comment by ProblematicDude** [comment]
I can confirm this. It's fixed even in the official build. Modifying  idea.propreties doesn't effect anything.

**Comment by crazy-max** [comment]
Thanks for your feedback

**Comment by puppleStar77** [comment]
please help. Even in the version from 2024.1.2, after installing the Flutter plugin, the plugin no longer gets uninstalled or installed. There are no errors, and it shows messages indicating successful installation or removal, but even if I restart or reinstall Android Studio or reboot my system, the Flutter plugin remains installed. Why is this happening? It’s driving me crazy.”
