### ISSUE TITLE
Pointing out: VirusTotal is detecting 3 vulnerabilities, mostly as Malware.

### ISSUE THREAD

**Issue by Weej1** [portapps/android-studio-portable#18]
### Behaviour
This does not affect Desktop as badly as mobile. On cell/mobile, the first thing you can see is a linked exe file that actually takes you to the VirusTotal link. There at the top, it shows 3 issues found. I know the 'Assets' dropdown is where the actual downloads are. But it's not clear and the 3~4 virus alerts may not seem reassuring to first-time visitors. ( I assume these are false positives but let me know if I'm wrong)
   
#### Steps to reproduce this issue

1. go to Github link via cell phone and click on exe link
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6381159/90305949-b55efe00-dee5-11ea-83ba-98695efeb1bd.png)

2. End result shows multiple Virus alerts
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6381159/90305954-ce67af00-dee5-11ea-9c52-e285916529e9.png)

#### Expected behavior

> VirusTotal should report an all-clear status and actual links to the portable app should be more prominent, especially on mobile devices.

**Comment by crazy-max** [comment]
Sometimes Antivirus scanner reports that a program is infected with a Virus or Trojan, even when the program is not really infected with any malicious code. This kind of problem is known as "False Positive". In other words, [Antivirus companies cause a big headache to small developers](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/).

As stipulated in the [FAQ](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper), those detections are generic. Most likely based on a heuristic detection and more prone to be false-positive and this [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to report this to your Antivirus software vendor as a false positive.

See also portapps/portapps#68 and https://github.com/search?q=org%3Aportapps+antivirus&type=Issues. Thanks for your support.
