### ISSUE TITLE
Error when try to update app (Some conflicts were found in the installation area: uninstall.exe)

### ISSUE THREAD

**Issue by MisiekDP** [portapps/android-studio-portable#26]
### Behaviour

Error when try to update app.
_Some conflicts were found in the installation area._
_Some of the conflicts below do not have a solution, so the patch cannot be applied_
_File: uninstall.exe_
_Action: Update_
_Problem: Modified_
_Solution: NONE_

#### Steps to reproduce this issue

1. Run the app.
2. Update the app.
3. After download I get an error.

#### Expected behaviour

> The app should be updated to newer version using update package (without error).

#### Actual behaviour

> The app is not updated (update will be cancelled by this error).

### Configuration

**App release / arch (ex. 1.0.0-2 win64)**
Android Studio 4.0.1, Build #AI-193.6911.18.40.6626763
Runtime version: 1.8.0_242-release-1644-b01, amd64

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Pro x64

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/22171619/99895383-6b29ad80-2c88-11eb-96ac-114d4edc9302.png)

### Screenshots

![image](https://user-images.githubusercontent.com/22171619/99895100-a081cb80-2c87-11eb-9193-bac5e7f76adf.png)

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
[android-studio-portable.log](https://github.com/portapps/android-studio-portable/files/5578963/android-studio-portable.log)

**Comment by crazy-max** [comment]
@MisiekDP Thanks for your feedback. Actually `uninstall.exe` is removed for portapp package, that's why you have conflicts when updating. In `Action` you can choose skip I think?

**Comment by MisiekDP** [comment]
@crazy-max Yeah bro. I can't change anything in these fields :/

**Comment by crazy-max** [comment]
Should work with latest release.
