### ISSUE TITLE
In folder android-studio-portable\data\.android there is subfolder also named .android

### ISSUE THREAD

**Issue by yetangye** [portapps/android-studio-portable#6]
### Behaviour
In folder android-studio-portable\data\.android there is subfolder also named .android
Is this right?

#### Steps to reproduce this issue

1. Upgrade android studio portable to 3.5.3
2. Create or open a project

#### Expected behaviour

> Tell me what should happen
I suspect data\.android\.android folder is some miss.

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
3.5.3-win64

**Operating system (ex. Windows 10 Pro 64 bits)** :
Win 10 Pro 64 bits

**Winver screenshot** :
Win version is 1909 (OS inner version is 18363.592)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@yetangye Yes this is totally fine.

* `data/.android` is the `ANDROID_SDK_HOME`
* `data/.android/.android` is the `ANDROID_EMULATOR_HOME`
